### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by timhappy** [ipa320/cob_android#12]
The app crashes after some time. That time is not specific (from 30sec to 30min) 
I could not find any triggering event in usage. Occures also when not used. 
No festures like navigation or range view are used. 
@ipa-fmw @ipa-bnm

**Comment by floweisshardt** [comment]
could that be related to loosing wifi connection?

**Comment by timhappy** [comment]
I could not see any sign of reconnecting to a wireless. Shouldn't there be a notification? 
Also the driving was quite jerky. I don't know if that are lost massages or just delayed ones.

**Comment by benmaidel** [comment]
i do not think that this is related to loosing wifi connection. If wifi is gone, the internal nodes should try reconnecting to their topics / services. @ipa-tif Since when have you experienced this Problem? Only since the newest Version? Could you try the Version checked in in github?

**Comment by benmaidel** [comment]
By the way, there is a special repo for our internal android apps. See [here](https://github.com/ipa320/cob_android_apps). Future android app issues should be opened there.

**Comment by timhappy** [comment]
yes, it appears since the newest version from the day you showed me the distance map.
i know the repository cob_android but i wnated to keep urgent issues in cob4.

**Comment by benmaidel** [comment]
so can you try [this](https://github.com/ipa320/cob_android/tree/indigo_dev/apks) version?
If it complains installing you have to uninstall the old version and then install the new. Don't forget to adjust the settings in the app after reinstall.

**Comment by timhappy** [comment]
I installed the app. For an hour it is stable, but it crashed during viewing the visulisation tab. 
The funny think is that the arms do not abroad the wave-pattern anymore with this version. 
Joystick-mode does not work.

**Comment by benmaidel** [comment]
If I understood you correct, you are saying that the app is stable as long as you do not open the visualization tab? As soon as you open the vis tab it takes some time until the app crashes?
Joystick-mode: Have you reconfigured the topic names inside the app settings?
Wave-patterns: Sorry, I do not get it. You mean starting/stopping wave-patterns from Knoeppkes tab? Is it working with the PC Knoeppkes?
How long do you stay at IPA today? Will come by after B., then we could take a look on it together.

**Comment by benmaidel** [comment]
I just noticed that there is still an open PR with a new apk Version. Have you tried this one as well. I think this Version is still without the distance view.

**Comment by floweisshardt** [comment]
PR is merged and obviously stabilized app
