### ISSUE TITLE
change service type to std_srvs/Trigger

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_android#3]
cob_srvs/Trigger ist outdated, please use std_srvs/Trigger

**Comment by benmaidel** [comment]
hmm, i took a look at my source code and i could not find any dependency to `cob_srvs/Trigger`. So there shouldn't be any problem with the app. Can you explain where you experienced msg type errors?

**Comment by floweisshardt** [comment]
we just tested again on cob4-2: everything OK, no need for change. Marking issue as invalid and closing.
