### ISSUE TITLE
use non-blocking service calls with script server

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_android#4]
please set req.mode to False

This is especially important for "init all" to be executed in parallel.

**Comment by benmaidel** [comment]
i think req.mode is the wrong field to modify. `req.mode` specifies the type of motion to execute. For example: req.mode=omni => omnidirectional, req.mode=diff => differential.

There are two ways to resolve this issue.
- Change all sss method parameters inside script_server_android.py. Force calling non blocking sss methods.
- Introduce bocking parameter to Script.srv, set blocking/non-blocking from Android GUI and pass the parameter to the sss calls

**Comment by floweisshardt** [comment]
as discussed with @ipa-bnm we'll implement option 1 (always non blocking calls to sss in android script server).

**Comment by fmessmer** [comment]
@ipa-bnm @ipa-fmw can we close this as #9 was merged?

**Comment by benmaidel** [comment]
yes, we can close it
